zap:
  debugFileName: "..\\logs\\debug\\project-debug.log"
  infoFileName: "..\\logs\\info\\project-info.log"
  warnFileName: "..\\logs\\warn\\project-warn.log"
  errorFileName: "..\\logs\\error\\project-error.log"
  maxSize: 500
  maxAge: 28
  maxBackups: 3
app:
  addr: 127.0.0.1:80
  name: project-api
etcd:
  addrs:
    - "127.0.0.1:2379"