zap:
  debugFileName: "/logs/debug/project-debug.log"
  infoFileName: "/logs/info/project-info.log"
  warnFileName: "/logs/error/project-warn.log"
  errorFileName: "/logs/error/project-error.log"
  maxSize: 500
  maxAge: 28
  MaxBackups: 3
app:
  addr: 0.0.0.0:80
  name: project-api
etcd:
  addrs:
    - "etcd3:2379"