zap:
  debugFileName: ..\\logs\\debug\\project-debug.log
  infoFileName: ..\\logs\\info\\project-info.log
  warnFileName: ..\\logs\\error\\project-warn.log
  maxSize: 500
  maxAge: 28
  maxBackups: 3
redis:
  host: 127.0.0.1
  port: 6379
  password: 
  db: 0