app:
  addr: "127.0.0.1:8081"
  name: "project-user"
zap:
  debugFileName: "..\\logs\\debug\\project-debug.log"
  infoFileName: "..\\logs\\info\\project-info.log"
  warnFileName: "..\\logs\\warn\\project-warn.log"
  errorFileName: "..\\logs\\error\\project-error.log"
  maxSize: 500
  maxAge: 28
  maxBackups: 3
redis:
  host: "127.0.0.1"
  port: 6379
  password: 
  db: 0
grpc:
  addr: "127.0.0.1:8882"
  name: "project"
  version: "1.0.0"
  weight: 2

etcd:
  addrs:
    - "127.0.0.1:2379"
mysql:
  username: root
  password: root
  host: 127.0.0.1
  port: 3309
  db: msproject
jwt:
  accessExp: 7
  refreshExp: 14
  accessSecret: msproject
  refreshSecret: ms_project